### ISSUE TITLE
No animation after destroying a board

### ISSUE THREAD

**Issue by cvn** [shaack/cm-chessboard#10]
With 2.12.5, after destroying a board, animation doesn't work on new boards. This breaks the 2-click move style.

This is a regression caused by changes in #9. It looks like `stopAnimation` never gets reset.

**Comment by shaack** [comment]
This should work now (please test it) :). But I found another issue that problems would occur if multiple boards have simultaneously animations running, because of the global `animationRunning` in `ChessboardPiecesAnimation`.

**Comment by shaack** [comment]
Testpage: https://shaack.com/cm-chessboard/examples/create-and-destroy.html

**Comment by cvn** [comment]
Thanks, @shaack! I just had time to update to version 2.12.8 in my project. It's working very well now, and less global state always feels good.
