### ISSUE TITLE
[Feature request] Improvements to animations

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#100]
Hello!

Would it be possible to

a) Change the piece animation logic so that pieces always move at a defined speed. Currently you can set how long it takes for a piece to move from A to B, that means that if a piece only has to move a short distance and the animation speed is set to 1000ms for example, then it would move very slowly, whereas if a bishop, queen or rook has to cross a long distance, then it would appear to move much faster then when moving only one or two squares away. Ideally it would be possible to set the animation speed so that the pieces do not slow down and speed up depending on the distance they are crossing.

b) It would be nice to have an option to have animation effects such as ease-in and ease-out

Many thanks for considering this improvement!

**Comment by shaack** [comment]
ease-in and out is already build-in. The speed can not be individual per piece because in the animations many pieces could move simultaneously, and if they all have a different time to reach the target square this would make it much more complicated.
