### ISSUE TITLE
Are there typescript types available?

### ISSUE THREAD

**Issue by blasco** [shaack/cm-chessboard#102]
Hi, first of all thank you for such an amazing and intutive chessboard library. I like developing with typscript, I wonder if there are any typscript definition files provided or if somebody happens to know how they could be easily generated. Thank you in advance!

**Comment by shaack** [comment]
Thank you! But no, I will stay at vanilla JS.

**Comment by shaack** [comment]
OK, I will keep it open. Maybe someone knows the answer.

**Comment by blasco** [comment]
Oh, ok... thank you anyways
