### ISSUE TITLE
Problems with importing an extension from node.js context

### ISSUE THREAD

**Issue by shaack** [shaack/cm-chessboard#103]

**Comment by blasco** [comment]
Hi, is the package.json properly updated? My project fails to resolve the import of the markers:

This works:
```
import { Chessboard, INPUT_EVENT_TYPE, COLOR } from 'cm-chessboard';
```

but the following fails
```
import { Markers, MARKER_TYPE } from 'cm-chessboard/extensions/markers';
```

I think it might be related to the package.json of the npm published library.

Thank you for the support!

**Comment by shaack** [comment]
Hi, which version?

**Comment by blasco** [comment]
I installed today, in package.json I have:
 ```
 "cm-chess": "^2.4.2"
```

**Comment by shaack** [comment]
This is "cm-chessboard", not "cm-chess".

**Comment by blasco** [comment]
Sorry, my bad. This is the version:

```
    "cm-chessboard": "^6.0.2",
```

**Comment by blasco** [comment]
My guess is that the package.json in the library is only exposing Chessboard and not the extensions, but I'm not sure if that's the real issue and how to solve it.

in cm-chessboard package.json:
```
  "module": "./src/cm-chessboard/Chessboard.js",
```
But no references to the extension modules.

**Comment by shaack** [comment]
For me this looks mainly like an issue of the used transpiling software, because in ES6 you have no imports like `import { Chessboard, INPUT_EVENT_TYPE, COLOR } from 'cm-chessboard';` this is transpiling syntax.

**Comment by blasco** [comment]
Ok, I'll try to figure it out and let you know, thank you!

**Comment by shaack** [comment]
Nice, thank you.

**Comment by pnb** [comment]
Is this still an issue? I used to have this problem (cm-chessboard v4) but this week I upgraded to take advantage of new v7 features and I am also now able to import from NodeJS without any problems. I am not using all the extensions though, only Markers, PromotionDialog, and a couple custom extensions.

**Comment by shaack** [comment]
I don't think so and will close the ticket.

**Comment by Ivanov-Igor-V** [comment]
Hello! Could you explane please. Why import fron line 25 is working, but on 26 - not?

**Comment by shaack** [comment]
@Ivanov-Igor-V What do you mean with "is not working". Is there a failure or an exception?

**Comment by Ivanov-Igor-V** [comment]
> @Ivanov-Igor-V What do you mean with "is not working". Is there a failure or an exception? Do you use a framework or transpiling software?

i'm sorry its just misspelling in a word extensions
