### ISSUE TITLE
URLs not fully working in documentation

### ISSUE THREAD

**Issue by Paradis4432** [shaack/cm-chessboard#110]
in the readme or documentation, some of the Examples links not working properly for example

https://shaack.com/projekte/cm-chessboard/examples/extensions/chessboard-arrows-extension.html
https://shaack.com/projekte/cm-chessboard/examples/input-callbacks.html
https://shaack.com/projekte/cm-chessboard/examples/context-input.html
https://shaack.com/projekte/cm-chessboard/examples/extensions/chessboard-arrows-extension.html
https://shaack.com/projekte/cm-chessboard/examples/extensions/chessboard-accessibility-extension.html

**Comment by shaack** [comment]
Thanks @Paradis4432, fixed with version 7.3.3.
