### ISSUE TITLE
.getPosition() removes the fullmove number

### ISSUE THREAD

**Issue by djeetee** [shaack/cm-chessboard#112]
Hello,

getPosition() seems to strip the fullmove number from the returned FEN even if the board was initialized with a FEN that includes the fullmove number. In fact, it strips out everything past the pieces. For example: 

```
in: "r1bqkb1r/pp1ppppp/2n2n2/8/3NP3/8/PPP2PPP/RNBQKB1R w KQkq - 1 5"
out: "r1bqkb1r/pp1ppppp/2n2n2/8/3NP3/8/PPP2PPP/RNBQKB1R"
```

Any reason for that? 

Could the method be changed to maintain the FEN structure?

thanks

**Comment by shaack** [comment]
cm-chessboard is not intended for saving the state of a game, it has no logic implementing chess rules. cm-chessboard can do two things, display chess positions and allow the input of chess moves. Therefore cm-chessboard does not store the status of castling or the number of the move.

To manage the state of a chess game you need to use another module, like chess.js. See also the validate-moves example https://shaack.com/projekte/cm-chessboard/examples/validate-moves.html which does this.

**Comment by djeetee** [comment]
thanks Stefan. I am using chess.js and referencing the example your mentioned. What I asked for was more out of convenience in one particular use-case. All good and many thanks for your response.

**Comment by shaack** [comment]
Okay. Maybe I should update the documentation, to make it clearer, that the returned value is only the position part of a FEN, so it won’t look like a failure.
