### ISSUE TITLE
moveInput already enabled error

### ISSUE THREAD

**Issue by djeetee** [shaack/cm-chessboard#116]
after the upgrade to 7.6.5 i'm getting this error:

`Uncaught (in promise) Error: moveInput already enabled`

Was anything changed in `enableMoveInput()` to trigger this?

I will look a the code later, but i think it is because the user can jump back and forth between moves and I wanted to make sure input was enabled for the right color hence the extra 'enableMoveInput()`

This brings back my previous question about the method's behaviour when `color` is not specified.

thanks.

**Comment by shaack** [comment]
Yes, this now detects, when multiple `enableMoveInput()` are registered without `disableMoveInput()`. For every `enableMoveInput()` there should also be a `disableMoveInput()`.

**Comment by djeetee** [comment]
Fixed.

Btw, I'm following the structure of **validate moves example** but I wish I looked at the your playfield code earlier. I like it.

Onto the engine piece code.

thanks again Stefan.
