### ISSUE TITLE
How do people usually handle moving the rook post-castling?

### ISSUE THREAD

**Issue by willdelphia** [shaack/cm-chessboard#118]
Sorry if this isn't an issue with the library per se. But I have installed a chess engine along with this cm-chessboard to accept legal moves and if they are legal update allow them on the cm-chessboard instance using the drag and drop validation method. The issue is that the the rook will remain in place after a legal castling move. Is there a simple way to make the rook jump the king after a successful castle? Or will I have to code my own solution to make this happen. Thanks.

**Comment by shaack** [comment]
Hi. This is solved in the [Move Validation example](https://shaack.com/projekte/cm-chessboard/examples/validate-moves.html ).
You could also take a look at the ["Playfield" Extension](https://github.com/shaack/cm-chessboard-playfield), where everything is implemented in a more sophisticated way.
