### ISSUE TITLE
Arrows sometimes display wrong

### ISSUE THREAD

**Issue by blasco** [shaack/cm-chessboard#124]
I've updated to the latest version. I'm now using the assetsPath, as suggested:

```
    const config = {
      assetsUrl: 'assets/cm-chessboard/',
      extensions: [
        { class: Markers },
        { class: Arrows },
      ],
      responsive: true,
    };
    this.chessboard = new Chessboard(this.chessboardElement, config);
```

Everything seems to be working fine, but sometimes arrows display wrong:

![image](https://github.com/shaack/cm-chessboard/assets/3214400/9ed2bdf0-3455-41ba-aadd-53ff847e545e)

And I'm getting these errors:

```
Error: <marker> attribute markerWidth: Expected length, "undefined".
Error: <marker> attribute markerHeight: Expected length, "undefined".
```

What could be going on?

**Comment by blasco** [comment]
I was setting the structure of the assets wrong, now it seems to work fine. Never the less, I still get that error every time I get to draw an arrow:

![image](https://github.com/shaack/cm-chessboard/assets/3214400/0aa1ed3e-94d7-4a1b-8281-29a26d66e6e0)

**Comment by actor10** [comment]
What are you passing to "addArrow()"?

**Comment by blasco** [comment]
Hi, I'm passing this:

```
  public addArrow(arrow: {
    type: typeof ARROW_TYPE;
    from: string;
    to: string;
  }) {
    try {
      this.chessboard.addArrow(arrow.type, arrow.from, arrow.to);
    } catch (error) {
      console.warn('Error adding arrow:', error);
    }
  }

```

An ARROW_TYPE, a from and and a to

**Comment by shaack** [comment]
I am not sure, but it looks like your arrow has no `headSize` set. There is a working example online under this URL: https://shaack.com/projekte/cm-chessboard/examples/extensions/arrows-extension.html
