### ISSUE TITLE
Error on rendering the board

### ISSUE THREAD

**Issue by alfreale** [shaack/cm-chessboard#125]
I have updated the last version and I got this error:

ChessboardView.js:263 Uncaught TypeError: Failed to execute 'setTranslate' on 'SVGTransform': The provided float value is non-finite.
    at ChessboardView.drawPieceOnSquare (ChessboardView.js:263:19)
    at ChessboardView.redrawPieces (ChessboardView.js:230:22)
    at ChessboardView.handleResize (ChessboardView.js:128:18)
    at ResizeObserver.<anonymous> (ChessboardView.js:26:26)

I got this error only in Windows 10 and google chrome 115. Using Linux it works. It seems a bit strange that I got this error only on Windows, but this error appears only after the update.

**Comment by shaack** [comment]
Can you provide an online version of your implementation so I can check whats happening?

**Comment by alfreale** [comment]
Hi, It was my fault. I passed a wrong aspect ratio to the chessboard.

**Comment by shaack** [comment]
Okay, no problem :)
