### ISSUE TITLE
showPromotionDialog() always cancels

### ISSUE THREAD

**Issue by djeetee** [shaack/cm-chessboard#126]
Hey Stefan, 

showPromotionDialog() pops up the dialog as expected however, clicking any promotion piece causes the dialog to cancel (returns null). 

I noticed that the dialog looks different from the one in the cm-chessboard example. Mine has a black background and hovering over the pieces does not trigger the highlight. 

I thought it's picking up the color of the page which black. changing page background did not make a difference.

I have feeling that it is a layering issue. I am not setting z-index for any of the page elements.

Any thoughts on what is going on?

<img width="546" alt="image" src="https://github.com/shaack/cm-chessboard/assets/612096/b922f63b-b7d4-40e6-b371-fbf1163d1f1e">

**Comment by shaack** [comment]
Hi @djeetee, it looks, like you did not include the CSS for the dialog:
`<link rel="stylesheet" href="../../assets/extensions/promotion-dialog/promotion-dialog.css"/>`
You can also include the SCSS in the same folder, to your main SCSS, if it fits better.

**Comment by djeetee** [comment]
Bingo! That did it. Thank you for the prompt reply.
