### ISSUE TITLE
Implementation of premoves

### ISSUE THREAD

**Issue by woozimu** [shaack/cm-chessboard#127]
Can i enable square select after i moved? If i use async input handler, then it works, but there is an issue with animations.
On default it disables square select so i wonder can i somehow enable it.

**Comment by shaack** [comment]
What do you want to accomplish with this? Maybe coding an "Extension" would suit better. I need a bit more details.

**Comment by woozimu** [comment]
i want to implement premoves

**Comment by shaack** [comment]
More in the lichess oder chess.com style? They have a different approach.

**Comment by levallem** [comment]
Would it be possible to update the readme file?
