### ISSUE TITLE
Would it be possible to update the readme file? 

### ISSUE THREAD

**Issue by levallem** [shaack/cm-chessboard#130]
Would it be possible to update the readme file?
especially this part
After installation, copy the sprite in cm-chessboard/assets/images/ to your projects assets/images/ folder. If you put the sprite somewhere else you have to configure the location with {sprite.url: "./url/of/chessboard-sprite.svg"} (see section 'Configuration' below).

**Comment by shaack** [comment]
Thank you for your feedback. What was it exactly that you wanted to achieve and what got you stuck?

**Comment by levallem** [comment]
Hi shaack

I would like to start using cm-chessboard but I have not understood the instructions in the readme file.
I believe the instructions are from an older version of cm-chessboard.
After installation you indicate: After installation, copy the sprite in cm-chessboard/assets/images/ to your projects assets/images/
Images does not exist in your project.
  neither chessboard-sprite.svg
Maybe for someone who comes from previous versions they will be familiar.
But in my case I just discovered cm-chessboard and with these instructions I have not been able to get it up and running.
That's why I ask if you can update the readme file please.

**Comment by shaack** [comment]
Ah, I get it. That was kind of out of my focus, sorry. 

I have now done a huge update of the README and added a "first steps" section: https://github.com/shaack/cm-chessboard#installation-and-first-steps

I would love to get some feedback if this works well and is understandable.

**Comment by levallem** [comment]
Thanks shaack, now it is much clearer and easier to install.
I'm testing with cm-chessboard in my project.
