### ISSUE TITLE
2 Player on same PC 

### ISSUE THREAD

**Issue by ezz3r** [shaack/cm-chessboard#132]
Hello guys i am not that good at JS and etc. 
But i cant figure out how i make an chess game where the player is switched. Would be nice if you could help me.

**Comment by actor10** [comment]
What do you mean by "switched"?   You want black at the bottom of the screen?   That's the "orientation" field

**Comment by shaack** [comment]
You could use [chess-console](https://shaack.com/projekte/chess-console/examples/play-both-local.html), which is based on cm-chessboard but a fully functional chess UI with sound and everything.

**Comment by ezz3r** [comment]
chess-sonole looks good! will try that, dankeschön :)

**Comment by ezz3r** [comment]
So i tried chess console but i can't integrate it with php. 
I have to make a chess game with php for a school project. 
I want that you can play against each other on different pc's (the communication is through a database). Could someone please recommend me an library for that? HTML etc is not my strenght, its not fun for me :(
