### ISSUE TITLE
Example code for local play

### ISSUE THREAD

**Issue by ezz3r** [shaack/cm-chessboard#133]
Hello guys i am having a hard time with JavaScript, so I wanted to ask if someone could provide me an example code for an valid input.
So only the moving, not the switching between players etc.

**Comment by ezz3r** [comment]
I just need an valid move input independent on the piece color moving. I tried to understand by reading the code in "validate-moves.html" example but i can't understand it or get it work with my idea. So would be nice if you could help me

**Comment by shaack** [comment]
In that case, you have to learn JavaScript first. This is the wrong place for such a  base level support.
