### ISSUE TITLE
setPosition for new Chess()?

### ISSUE THREAD

**Issue by ezz3r** [shaack/cm-chessboard#135]
"board.setPosition(chessboardState, true);"

So basically i am getting the chess fen from the database and it updates it visually. But not in the "chess engine". Is there a setPosition function for const chess?

"const chess = new Chess()"

**Comment by ezz3r** [comment]
Ok i just found through testing. Solution: chess.load(fen)

**Comment by shaack** [comment]
It has mostly the same API as chess.js because it is based on chess.js
