### ISSUE TITLE
Is there a drag & drop to place pieces on the board?

### ISSUE THREAD

**Issue by actor10** [shaack/cm-chessboard#139]
Is there functionality to have a set of white & black pieces on the side and drag them onto the board to build up a position?

**Comment by actor10** [comment]
I see a few closed issues about this from 2022 but nothing indicating this has been added. I looked at the FEN editor.

**Comment by shaack** [comment]
No, the cm-chessboard has no plugin with such a functionality. But feel free to write it. 🙂 The cm-fen-editor editor works nice on my website: https://www.chessmail.de/board-editor therefor I have no intention of creating another kind of FEN editor.

**Comment by actor10** [comment]
I'm looking at adding a "sidecar" list of pieces that can be dropped on the board. This would be more like HIARCS on the Mac where you click on a piece and then click on squares where that piece is deposited.
