### ISSUE TITLE
How to fetch the marked squares

### ISSUE THREAD

**Issue by programarivm** [shaack/cm-chessboard#142]
Can the marked squares be retrieved from the board object?

![screencapture-shaack-projekte-cm-chessboard-examples-validate-moves-html-2024-07-09-09_53_25](https://github.com/shaack/cm-chessboard/assets/4062000/47a72d3e-c9e7-4813-bc02-5a0c2839a46c)

In this particular example, how would e3 and e4 be retrieved once the e2-pawn has been clicked on?

https://shaack.com/projekte/cm-chessboard/

```js
    import {Chessboard} from "./src/Chessboard.js"
    import {FEN} from "./src/model/Position.js"
    import {Chess} from "https://cdn.jsdelivr.net/npm/chess.mjs@1/src/chess.mjs/Chess.js"

    const chess = new Chess()
    const board = new Chessboard(document.getElementById("board"), {
        position: FEN.start
    })
    const interval = setInterval(() => {
        makeRandomMove()
        board.setPosition(chess.fen(), true)
    }, 500)
    function makeRandomMove() {
        if(chess.game_over()) {
            chess.reset()
        }
        const possibleMoves = chess.moves()
        if (possibleMoves.length === 0) {
            clearInterval(interval)
            return
        }
        const randomIndex = Math.floor(Math.random() * possibleMoves.length)
        chess.move(possibleMoves[randomIndex])
    }
```

Thanks for the help,

**Comment by shaack** [comment]
Yes, it can, just read the documentation https://github.com/shaack/cm-chessboard/blob/master/src/extensions/markers/README.md (getMarkers)
