### ISSUE TITLE
Implementation of fairy chess pieces

### ISSUE THREAD

**Issue by programarivm** [shaack/cm-chessboard#143]
I was able to successfully add a fairy chess piece to my clone of this repo, and now was wondering if fairy chess pieces could also be added to shaack/cm-chessboard.

See:

- https://github.com/chesslablab/cmblab/issues/1

![figure_02](https://github.com/user-attachments/assets/98d53698-6c71-45d9-be3c-8d6893e3fae1)

**Comment by shaack** [comment]
Hi, thank you for the creation, but the cm-chessboard core should be reduced to the minimum.
