### ISSUE TITLE
Enable Premove Allow user to drag his own pieces even if it is not his turn

### ISSUE THREAD

**Issue by thewhisperinyourears** [shaack/cm-chessboard#145]
So I am trying to figure out how to allow the user to drag his own pieces when is not his turn i am already doing         `board.enableMoveInput(inputHandler, orientation);`

But I want to allow the user to drag his own pieces so I can add premove. 

Anyone tried adding premove before?

**Comment by thewhisperinyourears** [comment]
This is the current inputHandler i have:

```
const inputHandler = (event) => {
  if (event.type === INPUT_EVENT_TYPE.movingOverSquare) {
    return;
  }

  if (event.type !== INPUT_EVENT_TYPE.moveInputFinished) {
    event.chessboard.removeLegalMovesMarkers()
  }

  if (event.type === INPUT_EVENT_TYPE.moveInputStarted) {
    const moves = game.moves({square: event.squareFrom, verbose: true})
    event.chessboard.addLegalMovesMarkers(moves)
    return moves.length > 0

  } else if (event.type === INPUT_EVENT_TYPE.validateMoveInput) {
    const move = {from: event.squareFrom, to: event.squareTo, promotion: event.promotion}
    const result = game.move(move)

if (result) {
    event.chessboard.state.moveInputProcess.then(() => { 
      event.chessboard.setPosition(game.fen(), true)
    })
    return true;
} else {
        let possibleMoves = game.moves({square: event.squareFrom, verbose: true})
        for (const possibleMove of possibleMoves) {
            if (possibleMove.promotion && possibleMove.to === event.squareTo) {
                event.chessboard.showPromotionDialog(event.squareTo, COLOR.white, (result) => {
                    if (result.type === PROMOTION_DIALOG_RESULT_TYPE.pieceSelected) {
                        let pmove = game.move({from: event.squareFrom, to: event.squareTo, promotion: result.piece.charAt(1)})
                        event.chessboard.setPosition(game.fen(), true)
                    } else {
                        event.chessboard.setPosition(game.fen(), true)
                    }
                })
                return true
            }
        }
    }
    return result
}

}
```

**Comment by shaack** [comment]
Hi, I implemented pre-moves in [chess-console](https://shaack.com/projekte/chess-console/) which uses cm-chessboard. chess-console is used in the live-chess area of my chess server chessmail.de.
See the example page for chess-console with pre moves: https://shaack.com/projekte/chess-console/examples/game-with-random.html
In chess-console multiple pre moves are implemented, like in chess.com.

Single pre-moves are also possible, I've done this in https://github.com/shaack/cm-chessboard-playfield which is an extension for cm-chessboard. cm-chessboard-playfield has no dependencies besides cm-chessboard. chess-console needs bootstrap and has way more functionality, like the display of moved history, captured pieces and new game dialog.

Hope that helps. Just ask, if you want to know more.

**Comment by thewhisperinyourears** [comment]
So the premove is not don in the inputHandler?

**Comment by thewhisperinyourears** [comment]
Are you still maintaining this one?

**Comment by shaack** [comment]
Hi, this is an OpenSource project. Open Source means, that I provide the source code for free under the MIT license but it does not mean, I will give fast support for free. To clarify: cm-chessboard ist meant as an input control for chess moves, the validation and other logic has to be implemented outside of the input. Think of it like a `<input type="text"/>`. This input also does not validate text, it just allows the input. With cm-chessboard you can display and input chess moves. Using it does not exempt you from learning javascript and coding a logic around it. You can also contact me, if you want professional support at my usual hourly rate, via https://shaack.com

**Comment by thewhisperinyourears** [comment]
But you have inputHandler. I will probably need to extend the cm-chessboard because there is no way at this time we can drag for a premove.

**Comment by shaack** [comment]
playfield is not big, just a cm-chessboard extension. It has premoves implemented:
[LocalPlayerWithPremoves.js](https://github.com/shaack/cm-chessboard-playfield/blob/main/src/players/LocalPlayerWithPremoves.js)


To extend cm-chessmail you can use the extension concept (like cm-chessboard-playfied uses), so the core code stays uneffected and keeps updateable. Mybe cm-chessboard-playfield is also exact, what you need.

**Comment by thewhisperinyourears** [comment]
@shaack well I like how you implemented inputHandler in cm-chessboard. What I don’t understand is why is not possible to enhance the inputHandler to implement the premoves. It is just so simple to use the inputHandler example you have with promotion and validation moves validation. 

Why is not possible to enhance the inputHandler function to allow premoves?

**Comment by shaack** [comment]
The input handler _allows_ premoves. The handler makes no difference who's turn it is and does no validation. in "Playfield" the input handler _is_ used to handle premoves (`this.playfield.chessboard.enableMoveInput`). The handler is enabled and never closed to accomplish this. The logic in the handler decides if it is a pre-move or a move. Read the code in `LocalPlayer` (no premoves) and `LocalPlayerWithPremoves`. 

```js
if (!this.playfield.chessboard.view.moveInputCallback) { // enable it only once on first request
            this.playfield.chessboard.enableMoveInput((event) => {
                return this.chessboardMoveInputCallback(event, moveResponse)
            }, this.playfield.props.playerColor)
        }
```

**Comment by shaack** [comment]
> Thanks. Yeah I was not expecting fast or anything support. I just read that playfield will supersede console and I thought it would have the same effect here. Anyway thanks.

To be clear, playfield will not supersede chess-console, playfield is meant to be a part of chess-console in future. chess-console does way more in handling chess-games, like moves history, captures pieces. playfield is just an cm-chessboard extension to handle validation, premoves, promotion and sound.

**Comment by thewhisperinyourears** [comment]
@shaack I like the LocalPlayerWithPremoves but is not as extensible as creating my own inputHandler. The reason is that I do a lot more then just locally premoving. For example i sent the move over a websocket etc. If I use the playfield I will need to go into your code to extend it to my use. I prefer inputHandler because is just a function I can create and extend. So in the next update to github if you changed your LocalPlayerWithPremoves my changes will be overwritten. I can always use game.turn() from chess.js to check the turn and make a decition based on that.

**Comment by shaack** [comment]
@thewhisperinyourears  I also use websockets with cm-chessboard in my chess server [chessmail.de](https://www.chessmail.de). It is used there by over 3000 active users. How about creating a `RemotePlayer` to handle the moves via websocket. This is the way it was meant to in `Playfield` and the way I implemented in on my server.

**Comment by thewhisperinyourears** [comment]
@shaack but you see my point about not editing your LocalPlayerWithPremoves? It just bafles me that I cannot enhance cm-chessboard inputHandler to have premoves.. I can use chess.js to validate etc., and determine the turn. Why does it need to be this hard?

**Comment by shaack** [comment]
It is not hard. It is just not trivial to understand what I did, and it is not possible for me to clarify it within the limits of possible expenditure.

**Comment by thewhisperinyourears** [comment]
I was able to do it! I just didnt understand some parts of the inputHandler.  Now is working like a charm! I didnt rely on playfield just plain inputHandler.
