### ISSUE TITLE
can't yarn add package

### ISSUE THREAD

**Issue by biowaffeln** [shaack/cm-chessboard#16]
I tried installing the package with ```yarn add cm-chessboard``` and got the following error message:

```
error C:\Users\Mark\Documents\Coding Projekte\chess-notation\node_modules\cm-chessboard: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments:
Directory: C:\Users\Mark\Documents\Coding Projekte\chess-notation\node_modules\cm-chessboard
Output:
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'web-module-linker'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Mark\Documents\Coding Projekte\chess-notation\node_modules\cm-chessboard\postinstall.js:6:25)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)

```

Any idea what the problem could be?

**Comment by shaack** [comment]
The 'web-module-linker', which is an devDependency is needed for the postinstall.js script. It should work, if you install 'web-module-linker' before as global. The problem is: I don't know how to ensure that the dependency is installed before the postinstall.js is running.

**Comment by shaack** [comment]
Should be the same problem with npm.

**Comment by shaack** [comment]
I moved the 'web-module-linker' from _devDependency_ to _dependency_. (v2.13.7) Does it work now?

**Comment by biowaffeln** [comment]
Well, web-module-linker got installed first, so that worked, but this time I got the following  error message

```
C:\Users\Mark\Documents\Coding Projekte\chess-notation\node_modules\cm-chessboard: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments:
Directory: C:\Users\Mark\Documents\Coding Projekte\chess-notation\node_modules\cm-chessboard
Output:
mkdir lib
Linking ..\..\svjs-svg\src\svjs-svg => ./lib/svjs-svg (dir)
fs.js:1031
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink '..\..\svjs-svg\src\svjs-svg' -> 'C:\Users\Mark\Documents\Coding Projekte\chess-notation\node_modules\cm-chessboard\lib\svjs-svg'
    at Object.fs.symlinkSync (fs.js:1031:18)
```

**Comment by biowaffeln** [comment]
I just tried it out, the problem is indeed symlinks + admin rights. If I ```yarn add``` it in a powershell with admin rights, the installation will work.
Is it really necessary to use web-module-linker? After all, your README still says "no Dependencies except svjs-svg" 😜

**Comment by shaack** [comment]
Nice, thanks. For now an info to Windows users is the best solution. I think, when I have some time left in future, I will create a packaged distribution which combines svjs-svg and all chessboard classes and allows easy using cm-chessboard without symlinks.
