### ISSUE TITLE
on jQuery tabs doesn't work

### ISSUE THREAD

**Issue by LocutusOfPenguin** [shaack/cm-chessboard#18]
Gen a chessboard inside a tab which is not visible at start, seems to not work (see code)
When I deactivate the jQuery Tab script, or move the board div to top, it works.

For me it seems that the ChessBoardView gets height & width of 0 in error case's.
Can y take a look? Actually I need it for "framework7" (also not working on tabs)
but I made this small example - its basically the jQuery Tab example, with your chessboard in Tab2.

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cm-chessboard</title>
    <link rel="stylesheet" href="./styles/jp.css"/>
    <link rel="stylesheet" href="./styles/cm-chessboard.css"/>

    <link rel="stylesheet" href="jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="jquery-1.12.4.js"></script>
    <script src="jquery-ui.js"></script>
    <script>
       $( function() {
          $( "#tabs" ).tabs();
       } );
    </script>

    <meta name="viewport" content="width=device-width, user-scalable=yes, initial scale=1.0"/>
</head>
<body>
<h1>cm-chessboard</h1>

<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Nunc tincidunt</a></li>
    <li><a href="#tabs-2">Proin dolor</a></li>
    <li><a href="#tabs-3">Aenean lacinia</a></li>
  </ul>
  <div id="tabs-1">
    <p>Proin elit arcu, rutrum commodo Curabitur nec arcu.</p>
    <div class="board" id="board"></div>
  </div>
  <div id="tabs-2">
    <p>Morbi tincidunt, dui sit amet facilisis feugiat</p>
    <div id="new"><p>Insert here</p></div>
  </div>
  <div id="tabs-3">
    <p>Mauris eleifend est et turpis. Duis id erat.</p>
  </div>
</div>

<script type="module">
    import {Chessboard} from "./src/cm-chessboard/Chessboard.js"

    const board = new Chessboard(document.getElementById("board"), {
        position: "start"
    });
</script>
</body>
</html>`

**Comment by shaack** [comment]
Thanks for your inquiry. I take a look next week.

**Comment by LocutusOfPenguin** [comment]
Is there any progress?
Sorry for re asking, but 1w is over.

**Comment by shaack** [comment]
Hello, I'm sorry, I haven't gotten to that yet. I will try to test it during the next week.

**Comment by LocutusOfPenguin** [comment]
[fehler.zip](https://github.com/shaack/cm-chessboard/files/3819511/fehler.zip)

**Comment by LocutusOfPenguin** [comment]
dein eMail Provider erlaubt GARNIX (auch kein zip), argh....Oh Mann :-( Bin ja ein böser Hacker, haha

**Comment by shaack** [comment]
Okay :) Ich schau mir das heute Abend mal an.

**Comment by shaack** [comment]
**Solution:**
Initialize the tabs **after** the chessboard was displayed, cm-chessboard has a callback for that:
```
    new Chessboard(document.getElementById("board2"), {
        position: "start",
        sprite: {url: "../assets/images/chessboard-sprite.svg"},
        responsive: true
    }, () => {
        $("#tabs").tabs();
    })
```
