### ISSUE TITLE
Pawn promotion support?

### ISSUE THREAD

**Issue by domschl** [shaack/cm-chessboard#19]
Is there some support-GUI for pawn promotion available (a select-option for promotion to knight, bishop, rook or queen?)

**Comment by shaack** [comment]
cm-chessboard is just the chessboard. Pawn Promotion Support ist implemented in chess-console https://github.com/shaack/chess-console, which uses cm-chessboard. See it in Action here: https://www.chessmail.de/pages/chess-computer.html

**Comment by domschl** [comment]
Thanks for the pointer to chess-console. That project isn't suitable for my needs, since it adds external dependencies.
Anyway thanks for your work on cm-chessboard, it's a nice project!

**Comment by adityaj2003** [comment]
Hey, so I know you probably do not need this. But for anyone else, you could modify chess.js (which is imported in the script tag at the top) and use a modified version of chess.js downloaded on your local folder. I found this one which worked well for me - https://github.com/jhlywa/chess.js
