### ISSUE TITLE
Can i use it with react?

### ISSUE THREAD

**Issue by m-misha93** [shaack/cm-chessboard#20]
What about React. Can i use it?

**Comment by shaack** [comment]
Why not?

**Comment by m-misha93** [comment]
it render board, but move, animation not work

**Comment by shaack** [comment]
Can you provide a link to a testpage?

**Comment by m-misha93** [comment]
https://github.com/m-misha93/chess-react

**Comment by m-misha93** [comment]
change inputHandler. it work

**Comment by shaack** [comment]
Okay,... nice... can you give more details? Thanks.

**Comment by m-misha93** [comment]
use inputHandler like in example 
 inputHandler = (event) => {
    if (event.type === INPUT_EVENT_TYPE.moveDone) {
      const move = {from: event.squareFrom, to: event.squareTo}
      const result = this.game.move(move)
      if (result) {
        this.setState(() => ({
          fen: this.game.fen(),
          history: this.game.history({ verbose: true }),
          squareStyles: squareStyling({ toSquare: event.squareTo, history: this.game.history({ verbose: true }) }),
        }));

      } else {
        console.warn("invalid move", move)
      }
      return result
    } else {
      return true
    }
  }
