### ISSUE TITLE
No implementation for setting position by drag & drop

### ISSUE THREAD

**Issue by VolkovVlad** [shaack/cm-chessboard#22]
There is no solution for implemention ["spare pieces"](https://chessboardjs.com/examples#2006) out of the box. 
If this is a desired feature, but it won't be done anytime soon (I mean no work has started), I can try adding it by myself.

**Comment by shaack** [comment]
I thought about it, but then implemented an editor without draggable spare pieces: https://shaack.com/projekte/cm-fen-editor/ it it works not bad. But if you want, you can add the implementation of draggable spare pieces to cm-chessboard. I would prefer a kind of plugin-solution to not bloat the core code with extensions rarely needed.
