### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by huydhoang** [shaack/cm-chessboard#25]
Hi, is there any instructions/guidance to use cm-chessboard with React Native?
I read the issue usage with React but still not sure because RN doesn't utilize html dom.
Great chessboard module anyway!

**Comment by shaack** [comment]
Thanks. Unfortunately I have no experience in using cm-chessboard with React Native and haven't read anything about it yet. If you find out something I would be happy if you report about it. I might be able to give some help on detail issues.

**Comment by huydhoang** [comment]
Thanks. As I understand, cm-chessboard grabs the DOM element to insert content. So if using with RN, I probably have to modify that part of the source code. As for now, I'm experimenting it with React web.
Another one. Can you tell me which software you use to design the SVG sprites?

**Comment by shaack** [comment]
The sprites of the figures are based on the Wikimedia Commons FIgures https://commons.wikimedia.org/wiki/Category:SVG_chess_pieces/Standard
To make the right sprite for cm-chessboard from these figures I used InkScape https://inkscape.org/de/ in the beginning, but now I make the sprites and almost all design with Sketch https://www.sketch.com.

**Comment by huydhoang** [comment]
> The sprites of the figures are based on the Wikimedia Commons FIgures https://commons.wikimedia.org/wiki/Category:SVG_chess_pieces/Standard
> To make the right sprite for cm-chessboard from these figures I used InkScape https://inkscape.org/de/ in the beginning, but now I make the sprites and almost all design with Sketch https://www.sketch.com.

Thank you for introducing me to InkScape. It's been a great help. I was able to put the Staunty chess pieces together in the sprite file. But somehow, it's been misplaced all over the board.

Did the sprite format change since you moved to Sketch?

![screen](https://i.imgur.com/qoGUt6c.png)

**Comment by shaack** [comment]
I changed the sprite format with version 3.0. All pices must be 40x40 in size and must be on the same position (0,0) in the sprite. The sprite must look a bit like e1. :) You could send me the sprite to my email address in https://shaack.com and I can take a look.

**Comment by huydhoang** [comment]
I'm doing this project to learn React and didn't make the design by myself.

Staunty is my favourite piece set I found in the Lichess app. 
It is actually made available by the team under GPL-3 license.

It means it's free for personal and commercial use as long as you open source and track changes in your project.

The set can be found in the link below. But to save you from downloading the entire repo, I'm going to send you a zip file over email :-) 

https://github.com/ornicar/lila/tree/master/public/piece/staunty

**Comment by JonL12345** [comment]
> Thanks. As I understand, cm-chessboard grabs the DOM element to insert content. So if using with RN, I probably have to modify that part of the source code. As for now, I'm experimenting it with React web.
> Another one. Can you tell me which software you use to design the SVG sprites?

Hey @huydhoang, did you get cm-chessboard to play nicely with React? I am trying to get a React chessboard too.

**Comment by huydhoang** [comment]
> > Thanks. As I understand, cm-chessboard grabs the DOM element to insert content. So if using with RN, I probably have to modify that part of the source code. As for now, I'm experimenting it with React web.
> > Another one. Can you tell me which software you use to design the SVG sprites?
> 
> Hey @huydhoang, did you get cm-chessboard to play nicely with React? I am trying to get a React chessboard too.

Hi Jon,
cm-chessboard works with React, and in my specific use case, Gatsby.js.
But it has an issue during development: board will flicker as it keeps redrawing when you move chess pieces or resize window.
After playing around with cm-chessboard, I finally conclude that it's better for a React user to adopt [chessboardjsx](https://chessboardjsx.com/), which is already a React fragment. It's made for React.
In the mean time, I'm experimenting cm-chessboard with Svelte and they seem to work well together.

**Comment by shaack** [comment]
@huydhoang In the latest version of cm-chessboard, the caching was improved and therefore the flicker is gone. See also https://github.com/shaack/cm-chessboard/issues/23

**Comment by huydhoang** [comment]
> @huydhoang In the latest version of cm-chessboard, the caching was improved and therefore the flicker is gone. See also #23

This is very good news. I'll take a look at it again when I can.

**Comment by JonL12345** [comment]
> > > Thanks. As I understand, cm-chessboard grabs the DOM element to insert content. So if using with RN, I probably have to modify that part of the source code. As for now, I'm experimenting it with React web.
> > > Another one. Can you tell me which software you use to design the SVG sprites?
> > 
> > 
> > Hey @huydhoang, did you get cm-chessboard to play nicely with React? I am trying to get a React chessboard too.
> 
> Hi Jon,
> cm-chessboard works with React, and in my specific use case, Gatsby.js.
> But it has an issue during development: board will flicker as it keeps redrawing when you move chess pieces or resize window.
> After playing around with cm-chessboard, I finally conclude that it's better for a React user to adopt [chessboardjsx](https://chessboardjsx.com/), which is already a React fragment. It's made for React.
> In the mean time, I'm experimenting cm-chessboard with Svelte and they seem to work well together.

Thanks for letting me know. The fact it is fixed is a good thing. chessboardjsx relies on lots of dependencies, which adds a security risk, unlike cm-chessboard. I think the author has done a fantastic job at avoiding needing any dependencies and that is one of the reasons why I went for it.

It would be nice if it also had some of the square highlighting of the other boards when you click a piece to move it, showing the possible move options. But overall I am impressed.

**Comment by shaack** [comment]
@JonL12345 Thank you for your praise! cm-chessboard is reduced to the board, it does not contain any chess logic. To calculate which moves are possible you can use [chess.js](https://github.com/jhlywa/chess.js)  (or my ES6 version [cm-chess](https://github.com/shaack/cm-chess)). 
In cm-chessbaord, with the callback of `chessboard.enableMoveInput` and `INPUT_EVENT_TYPE.moveStart` you can get the start field and then mark fields with `addMarker`.
See [this example](https://shaack.com/projekte/cm-chessboard/examples/validate-moves.html) (move validation)  and also  [this](https://shaack.com/projekte/cm-chessboard/examples/input-callbacks.html) (mark fields)

**Comment by JonL12345** [comment]
You're welcome! Yes, already using chess.js linked into cm-chessboard now. With chessboard.js, they just do a shading of the square, as opposed to the circle. Do you think it would be easy enough to do different types of markers? e.g. currently has a circle, which is great for some use cases I need. But to show possible moves, is it modifiable to have an extra argument that determines what type of marker to display? e.g. addMarker(markerType)

I'm kinda talking aloud here, but think that would be possible for me to do, I hope!

**Comment by huydhoang** [comment]
> You're welcome! Yes, already using chess.js linked into cm-chessboard now. With chessboard.js, they just do a shading of the square, as opposed to the circle. Do you think it would be easy enough to do different types of markers? e.g. currently has a circle, which is great for some use cases I need. But to show possible moves, is it modifiable to have an extra argument that determines what type of marker to display? e.g. addMarker(markerType)
> 
> I'm kinda talking aloud here, but think that would be possible for me to do, I hope!

As per styling, I also think Jon has a point. The ability to add custom markers/piece set aside from default ones is a desirable feature. It would probably increase adoption for `cm-chessboard`. I wonder if you'd be welcoming these changes to the board's api, @shaack ? I can help as well.

**Comment by JonL12345** [comment]
While I'm at it, can it do arrows?

**Comment by shaack** [comment]
The ability to add custom markers is already build in. It's just not very well documented. The main hurdle is to add the marker to the sprite. With a program like InkScape or Sketch this should be relatively easy. 

Example: The circle marker is defined in SVG like this: 
```svg
<g id="marker2" transform="translate(2.000000, 2.000000)" fill="#000000" fill-opacity="0">
       <circle cx="18" cy="18" r="18"></circle>
 </g>
```
(a circle with the radius 18 and the center at 20/20)

Important is the id "marker2". You can set the marker with board.addMarker({class: "emphasize", slice: "marker2"})
"emphasize" is the css class, which defines the color of the marker.  "slice" is the id of the marker in the SVG.

So you can simply add a marker with id "marker3" or "myMarker" to the SVG, and then set it with addMarker({class: "myClass", slice: "myMarker"}) 

I hope this helped a little, just ask if you have any other questions about it.

...and sorry, arrows are not easy possible for now, this would have to be coded as a kind of extension.

**Comment by huydhoang** [comment]
Thank you, that's great! So what about adding optional arguments for markers to have scaling and direction?
Since we don't have to change the api, I figure this shouldn't be a burden to maintain.
And it's a nice thing for people who want to analyze long-term strategy on the board.

**Comment by shaack** [comment]
@huydhoang  I am not shure, but scaling and direction could eventually also be done via css. For arrows I would prefer something like board.addArrow(squareFrom, squareTo, style) (or „addPathMarker“ to keep it more generic)

**Comment by erjoalgo** [comment]
Sorry to re-open this issue, but I'd like to request a little more clarification on using cm-chessboard with react.

@JonL12345 @huydhoang Did you have to make any modifications to cm-chessboard to get it to work with React or React Native? If so, would you care to post a minimal example of cm-chessboard using React?

**Comment by JonL12345** [comment]
I've stopped programming nowadays since I have retired. I cannot remember
what I did to be honst.

Jon
