### ISSUE TITLE
Problems with XHR and Apache Cordova

### ISSUE THREAD

**Issue by LocutusOfPenguin** [shaack/cm-chessboard#28]
Hi,
im referring to #23 

for me at IOS it doesn't work. When I turn the cache on, I get this error:

2021-03-07 08:16:15.607257+0100 MyApp[9980:418063] Task <CBAAA092-8C6C-4C64-B2C2-F55E02043BB3>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=app://localhost/static/chessboard-sprite.svg, NSErrorFailingURLKey=app://localhost/static/chessboard-sprite.svg, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <CBAAA092-8C6C-4C64-B2C2-F55E02043BB3>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <CBAAA092-8C6C-4C64-B2C2-F55E02043BB3>.<1>, NSUnderlyingError=0x600001d782a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}

with cache = false, or the old version 3.4.5 it works.
But without cache, it seems to be no big difference to 3.4.5 looking at code.
Btw, you removed a lot of ";" why?

When I say "doesn't work" , it means, there are no pieces displayed (just the empty board) plus an error message.
I guess, cause its not an url instead a filepath and this XHR seems to have a problem with that.
Strangely on android it works even with cache.

**Comment by shaack** [comment]
Im normalen iOS Safari funtkioniert es ja. Meist Du mit Apache Cordova?

**Comment by shaack** [comment]
It works in the normal iOS Safari. You mean with Apache Cordova? Without ";" the code looks better. As I told already, the board uses the SVG "use" tag, to display pieces. Cache means, that the SVG is first copied to the HTML via XHR request.

Unfortunately, I have no experience with Apache Cordova. It doesn't seem to be a cm-chessboard problem, but a question about Apache Cordova. See also: https://stackoverflow.com/questions/57361051/cordova-xhr-requests-on-android-work-in-emulator-but-not-on-phones

**Comment by LocutusOfPenguin** [comment]
yes, im using Apache Cordova (framework7.io to be precise).

For the moment, i simply turn the cache off, and before i changed my code, to only redraw the board if its really needed.
For this, i keep a "hash" value for the last position send to your lib in my code (makes it alot more complex).

You might think about to have a function inside yr own lib if a redraw is really needed.

With my "hash", its better , but the users still see redraws when something changes...Without hash, it was unusable.

I probl. need to go back to the versions with pgn files, if i dont find a good solution, with the new svg version. With this (old) version, i even dont need this hash code. Always speaking about IOS only. Android is fine with either version.

**Comment by shaack** [comment]
Did you read about the scheme and hostname Options? https://stackoverflow.com/questions/42760400/unsupported-url-error-for-a-cdvfile 
There has never been a PNG version, I users SVG from the start. But I changes the Sprite loading with this commit https://github.com/shaack/cm-chessboard/commit/2eb28f7638a298119e9f5820ebd59b9995a68512#diff-e77ea436c96fca9d4c407a01940642c02decc0c487652f2b16b080343e156906
But this old version also worked with XMLHttpRequest
