### ISSUE TITLE
Navigating through histroy

### ISSUE THREAD

**Issue by JonL12345** [shaack/cm-chessboard#30]
I have created a button to go to the first/previous/next/last move, but having looked at the underlying code, I cannot work out how to navigate through the history. I also had a look at chess-console but couldn't work it out!

Do you have any simple pointers to how I can attach some code to my button that will let me move back and forth?

**Comment by shaack** [comment]
cm-chessboard is just the input element, it does not implement any chess rules or data storing. To hold the game data you have to use something like [chess.js](https://github.com/jhlywa/chess.js).

**Comment by JonL12345** [comment]
I am using chess.js. Spent all day on this trying to get it to navigate! I have built an array of fens called fenHistory to help with the navigation.

So far I have:

`onClick={() => {
                    board.current.setPosition(fenHistory[fenHistory-1])
                  }}`

That is for the "Previous move" button. I think I'm doing this all wrong, as it is not working!
