### ISSUE TITLE
Allow no border

### ISSUE THREAD

**Issue by LandonSchropp** [shaack/cm-chessboard#31]
I'm trying to disable the border, but the `style.showBorder` setting doesn't seem to work. For example, here's what I get with my current config:

``` json
{
  "responsive": true,
  "moveInputMode": 1,
  "sprite": {
    "url": "/static/chessboard-sprite-7ae4df542523aef7007536d2a99557d0.svg"
  },
  "style": {
    "showCoordinates": false,
    "showBorder": false
  },
  "position": "8/8/8/8/8/8/8/8 w KQkq - 0 1"
}
```

<img width="747" alt="Screen Shot 2021-03-15 at 6 37 01 PM" src="https://user-images.githubusercontent.com/361591/111234851-726d2200-85bd-11eb-8c44-48614364c3da.png">

I would just hide the border with CSS, but the squares are still offset from `0,0`, so my board would't align to other elements in my UI.

**Comment by LandonSchropp** [comment]
Shouldn't `borderSize` on [this line](https://github.com/shaack/cm-chessboard/blob/master/src/cm-chessboard/ChessboardView.js#L108) be set to `0`?

**Comment by shaack** [comment]
There's something to that. With "border", however, the wide margin is meant, in which the coordinates are then also, as on the page: https://shaack.com/projekte/cm-chessboard/examples/styles.html 

So there should be three types of border: none, a thin one and the wide one. I would say the property "showBorder" should be renamed to "border" and then "none", "thin", "wide" as parameters or something like that.

**Comment by LandonSchropp** [comment]
That makes sense. Or, as an alternative, you could make the border size configurable with parameters like `5px` or `10%` as well.

**Comment by shaack** [comment]
With 3.7.0 (https://github.com/shaack/cm-chessboard/commit/ddf5db7c190668afa6bea5530f6db2331283ca9b) you can now set the `props.style.borderType` to `BORDER_TYPE.none` or just "none". (`showBorder` is now deprecated, it was illogical) Example: https://shaack.com/projekte/cm-chessboard/examples/styles.html (boards 4 & 5) The width of the border was and is configureable via css. Thanks for your suggestion! I think it's better now.

**Comment by LandonSchropp** [comment]
Awesome! Thank you!
