### ISSUE TITLE
How to add AI  like this example？

### ISSUE THREAD

**Issue by ifredom** [shaack/cm-chessboard#33]
Since there are no other document examples, I don't know if there is such a method

[example](https://jsfiddle.net/Laa0p1mh/3/)

```

var cfg = {
    draggable: true,
    position: 'start',
    onDragStart: onDragStart,
    onDrop: onDrop,
    onMouseoutSquare: onMouseoutSquare,
    onMouseoverSquare: onMouseoverSquare,
    onSnapEnd: onSnapEnd
};
board = ChessBoard('board', cfg);
```

**Comment by shaack** [comment]
The cm-chessboard is not desktop (mouse) concentric, more mobile first. With devices like mobile phone or tablet, `mouseover` makes no sense in my opinion. More than 50% of all web user use a mobile phone. For move-input you use board.enableMoveInput like in this example: https://shaack.com/projekte/cm-chessboard/examples/enable-input.html After click (or) touch on the start-square (`INPUT_EVENT_TYPE.moveStart`) you can mark the possible moves in cm-chessboard this is way better than on mouseover.

**Comment by shaack** [comment]
The cm-chessboard is not mouse-concentric. With more than 50% mobile users in the web, `mouseover` makes no sense. For move input you can use `board.enableMoveInput` like in this example: https://shaack.com/projekte/cm-chessboard/examples/enable-input.html
So you can mark squares with possible moves on `INPUT_EVENT_TYPE.moveStart`. This is way more compatible than on `mouseover`.

**Comment by ifredom** [comment]
Thank you for your quick reply. I'll try this

**Comment by ifredom** [comment]
![image](https://user-images.githubusercontent.com/13759936/112445630-4eae9680-8d8a-11eb-9582-cac54a720db1.png)

when i build project,Prompt this. [example](https://github.com/ifredom/vue-chess-example)

```
  init(el) {
    var that = this;
    this.board = new Chessboard(el, {
      position: this.game.fen(),
      sprite: {
        url: "./chessboard-sprite-staunty.svg",
        grid: 40, // size
      },
    });
}
```

**Comment by shaack** [comment]
Requests to the local filesystem are not allowed from a browser. Have you tried to use a webserver? Under MacOS you can easily start one with 
```
> python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```

**Comment by ifredom** [comment]
Yes, I have. I wanted to do it because I found out `chessboard.js` ,You can run it directly without opening the service。

[simplg-ai-chessboard.zip](https://github.com/shaack/cm-chessboard/files/6205388/simplg-ai-chessboard.zip)

**Comment by ifredom** [comment]
Yes, I have. I wanted to do it because I found out `chessboard.js` ,You can run it directly without opening the service。

[simplg-ai-chessboard.zip](https://github.com/shaack/cm-chessboard/files/6205388/simplg-ai-chessboard.zip)

**Comment by shaack** [comment]
There is another possibility, if you set in the props `sprite.cache = false`, the sprite will not be fetched via XMLHttpRequest but only cached by the browser.
