### ISSUE TITLE
Default Markers Don't Work

### ISSUE THREAD

**Issue by LandonSchropp** [shaack/cm-chessboard#36]
Hey, just a heads up, it looks like the default markers in `MARKER_TYPE` don't work with the Wikimedia standard pieces sprite included in the library. Looking at the SVG, it seems to be missing the IDs specified in `MARKER_TYPE`.

**Comment by shaack** [comment]
It seems to work as expected. But I changed the IDs recently (from "marker1-3" to "markerFrame", "markerCircle", "markerSquare"). Maybe you just have to change the sprites to the current sprites from the repository. Example: https://shaack.com/projekte/cm-chessboard/examples/input-callbacks.html

**Comment by LandonSchropp** [comment]
Ah, I'll be that's it. Thanks!
