### ISSUE TITLE
Additional Animation

### ISSUE THREAD

**Issue by LandonSchropp** [shaack/cm-chessboard#39]
Hello again!

I'd love to see a new animation added to the Chessboard. If a move is canceled, it'd be great for the piece to animate back to its previous position instead of snapping back to it. I'm using this in a "wrong move" effect, and I think it'd be a bit less jarring if the piece would animate.

https://user-images.githubusercontent.com/361591/117080161-e943b300-ad02-11eb-8df7-dbebc1cb912d.mov

This suggestion could maybe be generalized to all pieces animating into a position rather than snapping when moved by the user, such as when you move a piece to the corner of a square.

https://user-images.githubusercontent.com/361591/117080390-56574880-ad03-11eb-9cdd-c12a21fde446.mov

**Edit**

Previously, this question contained an additional request for a casting animation, but that animation already existed and wasn't working due to a bug in my code:

> When the player castles, it would be nice if the rook animated to its new spot instead of appearing there. Here's an example of what it currently does:
> 
> https://user-images.githubusercontent.com/361591/117079973-818d6800-ad02-11eb-98c3-a5cff9b9d5d9.mov

**Comment by shaack** [comment]
The animation of the castling should work. You just have to `setPosition` the rook. Because setPosition is per default animated. See this example: https://shaack.com/projekte/chess-console/examples/play-both-local.html You just have to set the position from chess.js after the move.

**Comment by LandonSchropp** [comment]
Hmm, that's odd. I wonder if this is related to #37. I'll investigate my code to make sure I'm not calling `setPosition` in a funky way.

**Comment by shaack** [comment]
Yes, theoretical this should work. Did you try to call the second setPosition asynchronous? Just an idea.
```js
setTimeout(() => {
    this.chessboard.setPosition(to, animated)
})
```

**Comment by LandonSchropp** [comment]
Unfortunately, that doesn't seem to have any effect.

```
new Promise(resolve => {
  setTimeout(() => {
    cmChessboard.setPosition(chessboard.fen).then(resolve);
  });
})
```

**Comment by shaack** [comment]
Okay, just to test, what happens when you add a delay
```js
new Promise(resolve => {
  setTimeout(() => {
    cmChessboard.setPosition(chessboard.fen).then(resolve);
  }, 1000);
})
```

**Comment by shaack** [comment]
Yes, that would be a nice icing on the cake. :) Maybe I'll add it later, currently I have almost no time because of customer projects. If you want, feel free to create a PR, would be happy. One would still have to think a bit about possible side effects.

And yes, the moveDone callback must return `true`, or the move is marked as invalid and taken back. I didn't think of that either.

**Comment by LandonSchropp** [comment]
That makes sense. I'll see if I can take a crack at it if I get some free time first. 🙂 Thanks again!

**Comment by shaack** [comment]
Thank you for your contributions. It is great to make open source components and get feedback for the work.

**Comment by LandonSchropp** [comment]
Thank *you* for the awesome library. cm-chessboard is really great!

**Comment by shaack** [comment]
I will close this for now. We could open it again, if we decide to implement such additional animation.
