### ISSUE TITLE
Small UX Issue

### ISSUE THREAD

**Issue by LandonSchropp** [shaack/cm-chessboard#40]
In doing a little UX testing with my app, I noticed a couple of people getting stuck when one piece is selected, and another is clicked. Currently, cm-chessboard deselect the current square, and a second click then selects the new square. This caused a slight user perception that the board wasn't always responsive to mouse input.

https://user-images.githubusercontent.com/361591/117882665-30382800-b270-11eb-89e6-c61c17206568.mov

This differs from the behavior of Chess.com, where the new piece is selected on click.

https://user-images.githubusercontent.com/361591/117882762-45ad5200-b270-11eb-8340-c8cf3c4c73c2.mov

I'd expect the following behavior when a piece is currently selected and the board is clicked:

* If a new piece that can be moved is clicked, the new piece is selected.
* Otherwise, the current piece is deselected.

Thanks!

**Comment by shaack** [comment]
That's right, it makes sense. However, the chessboard does not do move validation, so the rule must be
- If a new piece of the same color is clicked, the new piece is selected.
- Otherwise, the current piece is deselected.

**Comment by shaack** [comment]
Implemented in v3.11.0, https://shaack.com/projekte/cm-chessboard/examples/validate-moves.html
Thanks for the suggestion, cm-chessboard is now a bit better to use

**Comment by LandonSchropp** [comment]
Thank you!
