### ISSUE TITLE
Displaying board in dialog box

### ISSUE THREAD

**Issue by JonL12345** [shaack/cm-chessboard#44]
I have a problem displaying the board in a modal dialog box, where I am using it for a context sensitive help popup.

My code below is supposed to show the board in the dialog box, but instead I get an error:

`Error: container element is null
`

Any idea where I am going wrong?

```
import React from 'react';
import { Typography } from '@material-ui/core';
import DialogTitle from '@material-ui/core/DialogTitle';
import DialogContent from '@material-ui/core/DialogContent';
import Paper from '@material-ui/core/Paper';
import {
  Chessboard,
  INPUT_EVENT_TYPE,
  MOVE_INPUT_MODE,
  COLOR,
} from 'cm-chessboard';

// import './styles/cm-chessboard.css';

export const MyFunction = props => {

  new Chessboard(document.getElementById('board3'), {
    position:
      'rn2k1r1/ppp1pp1p/3p2p1/5bn1/P7/2N2B2/1PPPPP2/2BNK1RR w Gkq - 4 11',
    orientation: COLOR.black,
  });

  return (
    <>
      <DialogContent dividers>
        <Paper id="board3"></Paper>
      </DialogContent>
    </>
  );
};
```

**Comment by shaack** [comment]
This means, that `document.getElementById('board3')` returns `null`, is not found. This doesn't look like an issue of cm-chessboard and I am not very familiar with React. I would say, `<Paper id="board3"></Paper>` is not available at the time, when the call is made.

**Comment by JonL12345** [comment]
Correct. I found that I was trying to create the chessboard before the board3 was rendered. The solution is to use useEffect on `new Chessboard(document.getElementById('board3')`, so that it is only run after board3 has rendered.
