### ISSUE TITLE
Export as SVG image

### ISSUE THREAD

**Issue by Nandakumar-M** [shaack/cm-chessboard#49]
Hi,

Since the board, markings, pieces are all in svg, is it possible to export the board (along with pieces, markings etc) as an svg image?

Regards,
Nanda

**Comment by shaack** [comment]
I think so. After generation the chessboard is just an inline Svg like every other inline SVG. Maybe this stackoverflow post could help you with this https://stackoverflow.com/questions/23218174/how-do-i-save-export-an-svg-file-after-creating-an-svg-with-d3-js-ie-safari-an
