### ISSUE TITLE
Console errors on window resize after destroying responsive board

### ISSUE THREAD

**Issue by cvn** [shaack/cm-chessboard#5]
Hi @shaack,

I'm really enjoying cm-chessboard. I'm using it in an SPA, where I'm creating and destroying boards frequently.

With version 2.11.26, when I use `responsive:true` and I call `destroy()`, I get errors on window resize.

```js
import {Chessboard} from "cm-chessboard";
const chessboard = new Chessboard(document.getElementById('myBoard'), {responsive: true});
setTimeout(() => chessboard.destroy(), 1000);
```
Now resize the window, and these errors appear in the console:
```
Uncaught TypeError: Cannot read property 'squares' of null
    at ChessboardView.drawPieces (ChessboardView.js?8d80:226)
Uncaught TypeError: Cannot read property 'orientation' of null
    at drawBoardDebounce.setTimeout (ChessboardView.js?8d80:149)
Uncaught TypeError: Cannot read property 'markers' of null
    at drawMarkersDebounce.setTimeout (ChessboardView.js?8d80:287)
```

I think the problem is that the [resize listener](https://github.com/shaack/cm-chessboard/blob/30118777bd51c4ab2ba5571017576cb96d734494/src/cm-chessboard/ChessboardView.js#L32-L40) isn't being removed when destroy is called.

**Comment by shaack** [comment]
Hi @cvn,
thanks for the detailed reporting. 👍 You have been right, I optimized the destroy() method and it should be fixed now. Could you please provide some feedback, if it now works for you. Thanks!

**Comment by shaack** [comment]
Added a testpage for creation and destroying of thousands of boards: https://shaack.com/projekte/cm-chessboard/examples/destroy-many-boards.html

**Comment by cvn** [comment]
Thank you so much @shaack, `destroy()` works perfectly now. That test page is pretty entertaining. :)
