### ISSUE TITLE
How to do move from input?

### ISSUE THREAD

**Issue by xFighter1209** [shaack/cm-chessboard#52]
How to do move on board from input, something like `board.doMove('e2e4');`. Is this possible

**Comment by shaack** [comment]
Positions are set with FEN notation. Just use setPosition().

**Comment by shaack** [comment]
Adding a movePiece() method could make sense, I will think about it.

**Comment by shaack** [comment]
Added a new method `movePiece(squareFrom, squareTo, animated = true)` with version 3.16.
