### ISSUE TITLE
No square when dragging piece out of board

### ISSUE THREAD

**Issue by LandonSchropp** [shaack/cm-chessboard#53]
When dragging a piece out of the board, I'm not seeing a `square` property populated on the event.

``` js
{ 
  chessboard: {…}, 
  type: "moveCanceled", 
  reason: "movedOutOfBoard", 
  square: undefined 
}
```

**Comment by shaack** [comment]
I am not shure if I understood your posting. The square property is used, if a move is canceled within the borders of a board, like clicking again on the same piece. When clicking out of the board, this property makes no sense.

**Comment by LandonSchropp** [comment]
I would expect this to indicate the piece that was removed from the board. Maybe that would make more sense as a `fromSquare` property. In my use case, I'm using this event to signal when the user is trying to remove a piece from the board while they're editing a position, so I need to know where that piece came from so I can remove it.

**Comment by shaack** [comment]
`squareFrom` and `squareTo` is no set, like in the `moveDone` Callback.

**Comment by LandonSchropp** [comment]
Thank you!
