### ISSUE TITLE
Can I animate a single piece using board positions?

### ISSUE THREAD

**Issue by haystacklab** [shaack/cm-chessboard#56]
I want to use the Knight piece to show how it can travel over the board using a set of input co ordininates. Can I start the board with a single piece and then leverage the animate functionality to show how the Knight moves on the board.
I tried using the board.setPosition method but it a bit complex and was wondering if there is a simple way to achieve my use case.

Thank you!

**Comment by shaack** [comment]
Yes, setPosition needs FEN, which you can generate with something like chess.js. Do you mean a method like `movePiece("e2","e4")`? Or what would be the best way to move the Knight?

**Comment by haystacklab** [comment]
Initially, I want to start with an empty board with an option to set the starting position for the Knight. I would then render the Knight at the chosen position using board.setPosition() method. Once the user selects the end position of the Knight, I will generate the path for reaching the destination. 
I want to be able to animate the movement of the Knight for each position in the path. I tried to achieve this using the setPiece and setPosition method, but I was not able to use the animations with this.

```
const board = new Chessboard(document.getElementById("board1"), {
        position: "empty",
        sprite: {url: "../assets/images/chessboard-sprite-staunty.svg"},
        animationDuration: 3000,
        style: {
            borderType: BORDER_TYPE.frame
        }
    })
    for (var i = 1; i < 9; i++) {
        await board.setPiece('h' + i, 'bn')
        await board.setPosition('empty')
    }
```
Another method I tried after seeing the `pieces-animation.html` is use the setPosition method. It was somewhat closer to my use case but it was too complex to achieve.
```
        await board.setPosition('///N////')
        await board.setPosition('////N///')
        await board.setPosition('/////N//')
        await board.setPosition('//////N/')
```
If you can guide me on what is the best way to move the Knight on the chessboard with animations, that would be really helpful.

Thanks!

**Comment by shaack** [comment]
You could use `setPiece(square, piece)` to set the Knight to its initial position. And then `movePiece(squareFrom, squareTo, animated = true)` to move the knight.
```js
board.setPiece("e4", "wn")
board.movePiece("e4", "c3").then(() => {
    board.movePiece("c3", "d5").then(() => {
        board.movePiece("d5", "f4")
    })
})
```

**Comment by haystacklab** [comment]
You mean create the method movePiece in the Chessboard class? Because the method is not available in the class. If I were to create the class, which methods should I use to execute the movement and the animation?

**Comment by shaack** [comment]
I created it today with version 3.16. See the Example "Knight dance" here https://shaack.com/projekte/cm-chessboard/examples/pieces-animation.html

**Comment by haystacklab** [comment]
Just saw the update. Thank you so much. Works like a charm. I have another request, I want to draw a line for each square the Knight has visited. Like the path covered. If you could point me in the direction, I will try to code it myself.. :)

**Comment by shaack** [comment]
This is more complicated, i've to think about it. For now, I can tell that drawing is made in the `ChessboardView.js`. You can draw in the SVG with the method `Svg.addElement(parent, name, attributes)`.
