### ISSUE TITLE
Is it possible to create a boardEditor with this package?

### ISSUE THREAD

**Issue by coffeeDev98** [shaack/cm-chessboard#57]
@shaack  Is it possible to make a basic board editor using this including spare pieces?

**Comment by shaack** [comment]
I recently create one with cm-chessboard as one of its components. It is also open source. Demo page: https://shaack.com/projekte/cm-fen-editor/

**Comment by coffeeDev98** [comment]
> I recently created a FEN editor with cm-chessboard as one of its components. It is also open source. Demo page: https://shaack.com/projekte/cm-fen-editor/

Can you suggest a PGN package that supports variations(RAVs)?

**Comment by coffeeDev98** [comment]
Can this package be used for writing PGN variations? @shaack 

https://github.com/shaack/cm-pgn

**Comment by shaack** [comment]
I think so, take a look at the unittests of this package. For now it has the issue that it can parse but not render variations.

**Comment by coffeeDev98** [comment]
But, parsing means that it can read PGN, right? Not write it... My use case is for creating a PGN for a game from the start to end, including any variations if possible.

**Comment by shaack** [comment]
Yes it can read PGNs with variations, but can not write them, because this is not yet implemented. However, to implement writing should not be so difficult.
