### ISSUE TITLE
Taking piece of the same color as taking piece with clicking

### ISSUE THREAD

**Issue by cenekp74** [shaack/cm-chessboard#58]
Is it possible to take same colored piece by clicking on it? I mean it is possible with dragging it, but with clicking it only allows to take opposite colored pieces. 
Thanks!

**Comment by shaack** [comment]
Everything is possible. But its not very easy.

**Comment by cenekp74** [comment]
Ty, deleting one if statement in ChessboardMoveInput did the job for me :)
