### ISSUE TITLE
How to cancel a move when right click occurs during piece drag.

### ISSUE THREAD

**Issue by tneisinger** [shaack/cm-chessboard#61]
Hello! I want cancel a move if the user right clicks while dragging a piece. Is that possible? That's how I cancel my moves when I'm playing on chess.com or lichess.org.

Is there a way to force the board to trigger a `moveCanceled` event? I know that I can detect right clicks by passing a handler to the `EnableSquareSelect()` method, but I haven't found a way to cancel a move from within that handler.

The current behavior seems to be that, if square selection is enabled, the dragged piece will be dropped in-place when a right-click occurs.

**Comment by shaack** [comment]
`EnableSquareSelect()` is more for selecting a square. I think to cancel a move the event should also be handled, when the pointer has moved out of the board. I first have to check the Lichess board and see how the mechanic works there.

**Comment by LandonSchropp** [comment]
Hello! I had someone reach out and request this feature. :)

**Comment by shaack** [comment]
Done with version 7.1.0

**Comment by LandonSchropp** [comment]
Thanks!
