### ISSUE TITLE
Markers above/below pieces

### ISSUE THREAD

**Issue by MrEnroke** [shaack/cm-chessboard#65]
Sometimes I need the "markers" to be positioned above or below the pieces. 
![image](https://user-images.githubusercontent.com/4182336/176625541-acdf9e36-cf68-4a52-a69d-c0b9b90e6fbc.png)

In the image, the "blue square" must be below the piece but the dot above.

I have committed a possible solution for it included in our fork: aa6a6ea.

**Comment by shaack** [comment]
Nice and thank you for contributing. I think the part with the markers I will integrate into core. Regarding the arrows (which are also included in the commit) I think they are also a candidate for a plugin/Extension/AddOn System, like the external pieces bar.

**Comment by shaack** [comment]
Now possible with extensions, see the arrows extension.
