### ISSUE TITLE
How to set a position with external pieces by drag&drop

### ISSUE THREAD

**Issue by MrEnroke** [shaack/cm-chessboard#66]
![image](https://user-images.githubusercontent.com/4182336/176669328-3cef80e1-9d77-4a90-a919-1428cd4299b5.png)

**Comment by MrEnroke** [comment]
Ok¡ Thank you four your answers.

Lichess solves it by including a div with pieces in svg format (https://lichess.org/editor). In our case (with drag&drop), I think we can replicate a similar behavior.

In my case it is an exercise for students to learn to place pieces on the board (¿start position?). My requirements are very simple, I need an area where the pieces are located and can be placed on the board, and that same space allows the pieces to be removed when they are dragged off the board. Board pieces are repositionable.

Something like this: 
![image](https://user-images.githubusercontent.com/4182336/176700930-e1d010e7-03e5-4cb3-86e8-d32cd5f7b574.png)

But this could be extended to a position generator for which you would need:
- get the fen
- possible castling
- Turn
And optionally:
- Flip board
- Configured positions 

The ability to include markers could be done with enableSelectSquare with the right button in the same way that it is done in lichess.

**Comment by shaack** [comment]
Did you discover my position editor at https://shaack.com/projekte/cm-fen-editor/ 
Maybe it helps as starting point. There is everything beside the drag&drop of pieces.
