### ISSUE TITLE
Create an "Arrows" extension

### ISSUE THREAD

**Issue by shaack** [shaack/cm-chessboard#69]
Create an Extension to add arrows to the board from this code https://github.com/shaack/cm-chessboard/commit/aa6a6ea7065fa09017d38fa1a5bb4a6d98514862 of @MrEnroke

**Comment by barakmich** [comment]
Hey! I was just about to look into adding this for myself and saw the related issues. If I understand your plan correctly, for making it an extension, it'd look something like adding the extension callback to `redrawBoard` and then letting the extension take it from there?

Relatedly with #70, perhaps there's an opportunity to make markers an extension too, and have an "abovePieceRedraw" and "belowPieceRedraw" callback/extension point... 

Anyway, if it'd be helpful I could take a look at it!

**Comment by barakmich** [comment]
I'm already on it -- added the extension to the API already and I hope to have a complete PR this week!

Cheers from midnight in California!

**Comment by shaack** [comment]
One more thing to consider. I think we don't need a specific time (before or after redrawing) to draw before or after the pieces, but one layer (group) before and another behind the pieces. Like `markersGroupBelowPieces` and `markersGroupAbovePieces` instead of `markersGroup`.

**Comment by shaack** [comment]
See the demo page of the Arrows extension: 
https://shaack.com/projekte/cm-chessboard/examples/extensions/chessboard-arrows-extension.html

**Comment by tbazelczuk** [comment]
There is a js error
`Uncaught TypeError: this.registerMethod is not a function
    at new Arrows (Arrows.js:34:14)
    at new Chessboard (Chessboard.js:100:34)
    at chessboard-arrows-extension.html:19:24`

**Comment by shaack** [comment]
Does clearing the browser cache helps?

**Comment by tbazelczuk** [comment]
Thanks, it's working fine right now :)
