### ISSUE TITLE
animated pieces

### ISSUE THREAD

**Issue by cvn** [shaack/cm-chessboard#7]
Hey @shaack,

This isn't really an issue, but more of a question.

I'd like to have chess pieces that use svg clip-path and svg animation. Like in this exmaple: http://files.vonnau.com/fiddle/svg-sprite-animated/animated_sprite.svg

I haven't been able to get this working with the current sprite sheet setup. How would you recommend going about this? Do you think extending svjs-svg to support clip-path is practical or more trouble than it's worth? This is a niche use case, so I don't think it's worth your time, but I thought you might have a better sense of where to start than me.

Thanks,
Chad

<details>
<summary>svg code</summary>

```svg
<svg id="animated_sprite" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="546.5701" height="54.5808" viewBox="0 0 546.5701 54.5808">
  <defs>
    <clipPath id="clip-path" transform="translate(0 -5.8631)">
      <circle id="circle_mask" cx="33.6533" cy="33.6533" r="23.6533" fill="none"/>
    </clipPath>
  </defs>
  <title>animated_sprite</title>
  <g id="piece">
    <g clip-path="url(#clip-path)">
      <g id="waves">
        <path d="M546.57,27.8631c-34.1589,0-34.1589-14-68.3179-14s-34.16,14-68.3207,14-34.16-14-68.32-14-34.1587,14-68.3173,14c-34.16,0-34.16-14-68.32-14s-34.1612,14-68.3225,14c-34.1628,0-34.1628-14-68.3257-14s-34.1628,14-68.3256,14" transform="translate(0 -5.8631)" fill="none" stroke="#fcf" stroke-miterlimit="10" stroke-width="16"/>
        <path d="M546.57,52.4439c-34.1589,0-34.1589-14-68.3179-14s-34.16,14-68.3207,14-34.16-14-68.32-14-34.1587,14-68.3173,14c-34.16,0-34.16-14-68.32-14s-34.1612,14-68.3225,14c-34.1628,0-34.1628-14-68.3257-14s-34.1628,14-68.3256,14" transform="translate(0 -5.8631)" fill="none" stroke="#fcf" stroke-miterlimit="10" stroke-width="16"/>
      </g>
    </g>
    <circle id="ring" cx="33.6533" cy="27.7902" r="23.6533" fill="none" stroke="#99f" stroke-miterlimit="10"/>
  </g>
  <animateTransform xlink:href="#waves" attributeName="transform" type="translate" from="-137 0" to="0 0" begin="0s" dur="2s" repeatCount="indefinite" />
</svg>
```
</details>

**Comment by shaack** [comment]
Hi Chad, 
before you put effort in this. Do you know that these animations will not work in Edge Browser? 
Stefan

**Comment by cvn** [comment]
I did not know that, but it’s not a problem. I assume it would just display the initial state, which would be ok. I’ll test this for myself later.

**Comment by shaack** [comment]
Can you send me an animated example sprite to shaack@gmail.com? I could then take a look what the problem is.

**Comment by cvn** [comment]
Hey @shaack, I emailed you an example, but I don't need help with this anymore. I got animated sprites working by adding SVG directly to the page instead of loading it through svjs-svg. It's a pretty cool effect, and I will be sure to share a link with you once this project goes live. Thank you very much for your time with this, I'm going to close the ticket.

**Comment by shaack** [comment]
Hi @cvn, ok nice! How did you add the svg directly? As an HTML tag? Anyway, I look forward seeing your project when it is live.

**Comment by cvn** [comment]
Yes, I added it as an html tag. I’m injecting it as part of my build, so it’s pretty clean.
