### ISSUE TITLE
null of removeElement

### ISSUE THREAD

**Issue by tbazelczuk** [shaack/cm-chessboard#78]
Hi,

I found a bug that sometimes occurs with below error

```
Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at Svg.removeElement (ChessboardView.js?42c8:522:1)
    at eval (PositionAnimationsQueue.js?5d8a:175:21)
    at Array.forEach (<anonymous>)
    at PositionsAnimation.animationStep (PositionAnimationsQueue.js?5d8a:173:1)
```

and refers to below line

```
 static removeElement(element) {
        element.parentNode.removeChild(element)
    }
```

**Comment by shaack** [comment]
Hi, thanks for your report. Can you provide some details under what circumstances the problem occurs?

**Comment by tbazelczuk** [comment]
I suspect this issue occurs when I change positions frequently.

**Comment by shaack** [comment]
Sorry, this is not a detailed error description. Will close the ticket because I can not reproduce the failure.
