### ISSUE TITLE
Any chance you could add a method to clear all arrows easily?

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#80]
I had a look at your Arrows extension and I can't seem to figure out an easy way of clearing all arrows. It would be nice if there was a simple `clearArrows` method. Or at the very least if the `getArrows` method returned an array including all existing arrows. At the moment the `getArrows` method seems counter intuitive as it requires that you pass it a `type`, `to` and `from`.

The `arrows` array is not exposed currently so there's no easy way to retrieve all existing arrows after which I could iterate over each and remove each arrow.

I know I can extend this extension but.. it would be nice if these basic features were included for all to use.

Apologies if I'm just completely missing something obvious and there's already a way to clear arrows easily.

Many thanks

**Comment by vesper8** [comment]
Anyway this was super easy to add.. maybe you'll consider adding it to the core extension

```

  clearArrows() {
    this.arrows.forEach((arrow) => {
      this.removeArrows(arrow.type, arrow.from, arrow.to);
    });
  }
```

**Comment by shaack** [comment]
Hi, to remove all arrows, just call `chessboard.removeArrows()` without parameters.

**Comment by shaack** [comment]
Wrote more documentation for the arrows extension, see: https://github.com/shaack/cm-chessboard#arrows-extension

**Comment by vesper8** [comment]
Thanks @shaack 

It's weird, I thought for sure I had tried calling `removeArrows` and `getArrows` with no parameters and I thought I got errors from doing this about a missing type parameter.. maybe it's because of the new warning you added after changing the parameter order in `5.1`... I'll try again... did you test this with the latest version too?

**Comment by shaack** [comment]
Yes it works with the latest version.

**Comment by vesper8** [comment]
@shaack Thank you I can confirm that the `removeArrows` works fine.. I don't know why I was having issues with it before.

On a side note, it would be fantastic if you could allow us to set the colour of arrows easily without having to fork the whole Arrows extension just to add a few more arrow types.

It would be nice if we could pass the arrow colour as a parameter to the `drawArrow` method, or if that's not easy, then let us pass a custom class and when can define the colour inside the class since this is how colours are currently defined.

**Comment by shaack** [comment]
Hi, to create new arrows, you don't have to fork the arrows extension, just create new types. Like this.
```js
const MY_ARROW_TYPE = {
    info: {class: "arrow-info", slice: "arrowDefault", headSize: 7},
   warning: {class: "arrow-warning", slice: "arrowDefault", headSize: 7},
   whatever: {class: "arrow-whatever", slice: "arrowDefault", headSize: 7}, 
}
```
then add the classes .arrow-info and .arrow-warning to your css. Done.
