### ISSUE TITLE
Any chance you can explain how to add a positionChanged listener?

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#81]
So I've created a super basic extension based on your sample code:

```
import { Extension, EXTENSION_POINT } from '~/cm-chessboard/src/cm-chessboard/model/Extension.js';

export class Tracking extends Extension {
  constructor(chessboard, props) {
    super(chessboard, props);
    
    this.registerExtensionPoint(EXTENSION_POINT.moveInput, (data) => {
      console.log(data);
    });
  }
}
```

It correctly logs to the console all the events I'm interested in listening to.

The problem is.. I'm misunderstanding how I can actually bubble those events one layer up where I'm initializing the chessboard.

I want to be able to do something like this:

```
    this.chessboard.onPositionChanged((event) => {
      console.log(event);
    });
```

So that my new extension can relay these events to my chessboard instance.

I'm sure this is dead simple but I can't figure out the syntax to make this happen yet... would love to hear your advice here. 

Many thanks!

**Comment by vesper8** [comment]
Hrm.. so with a little help from a friend I was able to make it work rather cleanly like this:

```

        extensions: [
          {
            class: Tracking,
            props: {
              emitter: (data) => this.$emit('tracking', data),
            },
          },
        ],
```

```

import { Extension, EXTENSION_POINT } from '~/cm-chessboard/src/cm-chessboard/model/Extension.js';

export class Tracking extends Extension {
  constructor(chessboard, props) {
    super(chessboard, props);

    this.registerExtensionPoint(EXTENSION_POINT.moveInput, (data) => {
      props.emitter(data);
    });
  }
}
```

**Comment by shaack** [comment]
This seems like a legitimate solution to your problem. May I ask you, why you want to handle the event in the layer where the board is initialized? You could also give "this.$emit" via props into the extension and call it from there. Like 
```
extensions: [
  {
    class: Tracking,
    props: {
      emitter: this.$emit,
    },
  },
],
```
and in your extension
```
this.props.emitter("tracking", data)
```
Or did I get something wrong?

**Comment by vesper8** [comment]
Thanks @shaack,

That's a good question as to why I want to handle some logic outside of the extension. I'm migrating from another chessboard and all my logic is at the "Vue" scope and moving everything into isolated extensions might make sense but it's a lot of work right now. For example I'm interacting with Stockfish and interacting with APIs when you do certain moves or complete certain lines... and I'm not sure that moving all of this inside the extension makes sense but it's something I need to think more about.

**Comment by shaack** [comment]
Ok, but you know, that for handling the moves you should not use and don't need an extension? It's done with `board.enableMoveInput(inputHandler, COLOR.white)`, like in this example https://shaack.com/projekte/cm-chessboard/examples/validate-moves.html 
In extensions you can not validate moves because the return values of the callbacks are ignored. Extensions are more ment for graphical enhancements, but I am also not sure and maybe I should allow moves validation from within extensions. This extension mechanic is quite new, so I  don't know where the journey will go.
