### ISSUE TITLE
News functions for cm-chessboard

### ISSUE THREAD

**Issue by ssommelet21** [shaack/cm-chessboard#84]
Hi Stefan,
I am really impressed by this nice developpement.
cm-chessboard is amazing.

Can i ask you a new function ? like setOrientation ;

async setOrientation(color, animated = false) {
}

Maybe called like this :

async setSprite(url, size, cache = true) {
...
}

And to be able to change the piece dynamically ?

Maybe :

setCssClass(theme), setShowCoordinates(abool = false) could be cool too ;-)

Regards : Stéphan.

**Comment by shaack** [comment]
Hi Stéphan. Thank you very much. It looks like you want methods to change the skin of the chessboard dynamically. But you could also destroy the the board and create another instance on the fly, which would look the same, or not? Cheers Stefan

**Comment by ssommelet21** [comment]
Hi ! yes of course, but is is really less elegant ;-)
This is like destroying the board for doing a rotation (thank to your setOrientation :-) )

**Comment by vesper8** [comment]
@shaack Just wanted to chyme in and say that I too would appreciate a means of changing the skin/sprite/notations dynamically in the future without having to destroy/re-recreate the board. It would be a nice-to-have feature for sure.

Cheers!
