### ISSUE TITLE
Is there a changelog anywhere?

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#85]
Always nice to see plenty of development on this awesome project.. but with things changing as often as they do.. APIs and what not, it would be useful to have access to a changelog. In the event there is already one somewhere, could you please point me in the right direction?

Many thanks!

**Comment by shaack** [comment]
Thanks, but no, there ist no extra changelog beside the git commit messages. You can view them with
```bash
git log --oneline
```
