### ISSUE TITLE
[Feature Request] allow the use of a textured background behind the board

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#88]
I'm trying to spice up my chessboard a bit and I've noticed that on platforms such as Lichess the chessboard isn't only plain colours but there's a subtle textured background behind the squares that gives it a more "real board" feel and makes the board look nicer.

I've been trying to apply textures to the SVG board created by cm-chessboard but so far I haven't found a way to do it.

I've been trying to apply the textures found here
https://www.svgbackgrounds.com/set/free-svg-backgrounds-and-patterns/
and here
https://projects.verou.me/css3patterns/

But to no avail yet.

I was wondering if you could help me figure out how to make this possible.. and possibly, if needed, make a modification to the library to allow for such a thing to be possible.

Many thanks!

**Comment by shaack** [comment]
I think this must be possible via css. Have you tried this?

**Comment by ssommelet21** [comment]
Hello.

I agree with shaack.
If you put in 1 ;

	background-image: url(https://lichess1.org/assets/_0tHtbz/images/board/blue-marble.jpg);
	background-size: cover;
	
And put for 2 3 and 4 : 

	fill-opacity: 0.1

Here is the display :

![texture_cm](https://user-images.githubusercontent.com/92539141/190989247-b18d8192-6daf-435b-a848-fba08efebb15.jpg)

**Comment by vesper8** [comment]
@ssommelet21 I don't understand what you're doing here.. what do you mean `put in 1, 2, 3 and 4` ?

I've made my squares transparent with `fill-opacity` but I still can't see the background.

I tried

```

.cm-chessboard {
  background-image: url(https://lichess1.org/assets/_0tHtbz/images/board/blue-marble.jpg);
  background-size: cover;
}

.cm-chessboard .board {
  background-image: url(https://lichess1.org/assets/_0tHtbz/images/board/blue-marble.jpg);
  background-size: cover;
}
```

I also tried applying it to a parent div of the chessboard.. but none of these makes the texture visible.

Could you share how you're applying the background css exactly?

Many thanks

**Comment by ssommelet21** [comment]
@vesper8 i did an update of my "React-cm-chessboard" just look at differences here :

https://github.com/ssommelet21/React-cm-chessboard/commit/ee17ba2fd00e0569f45416eb11b314aea6fa5d22

**Comment by vesper8** [comment]
Awesome!! That works beautifully! Thank you : )
