### ISSUE TITLE
Feature request "flush queue"

### ISSUE THREAD

**Issue by tbazelczuk** [shaack/cm-chessboard#89]
Hi, 

I've found two bugs.  Please see below description.

TypeError: Cannot read properties of null (reading 'parentNode')

PositionAnimationsQueue.js:145

```
case CHANGE_TYPE.move:
                    animatedItem.element = this.view.getPieceElement(Position.indexToSquare(change.atIndex))
                    animatedItem.element.parentNode.appendChild(animatedItem.element) // move element to top layer
                    animatedItem.atPoint = this.view.indexToPoint(change.atIndex)
                    animatedItem.toPoint = this.view.indexToPoint(change.toIndex)
                    break
```

... and sometimes removeElement has null element

```
static removeElement(element) {
    if (element.parentNode) {
      element.parentNode.removeChild(element)
    } else {
      console.warn(element, "without parentNode")
    }
  }
```

**Comment by shaack** [comment]
Under what circumstances does this occur?

**Comment by tbazelczuk** [comment]
It happens when you change position frequently.

**Comment by shaack** [comment]
Unfortunately, I can't reproduce this without an example page where the error occurs.

**Comment by tbazelczuk** [comment]
It happens when you change position during animation.

**Comment by tbazelczuk** [comment]
I would be nice to setPosition without animation and queue, just reset the board with initial fen

**Comment by shaack** [comment]
If you are are not able to provide an example page, I can not help you.

**Comment by shaack** [comment]
I can not help you, without an example page. This error does not exist in the demo page or any of my usages.

**Comment by tbazelczuk** [comment]
Hi, unfortunately I can't reproduce it. I suspect react setState overhead and async events may cause it.

I prepared example how animation queue works when you mouse over on buttons. When you mouse over very quickly and many time the animation is queued. It would be nice to have reset method and cancel queued animations.
https://github.com/tbazelczuk/cm-chessboard/blob/example/examples/preview.html

**Comment by tbazelczuk** [comment]
Sure, but resetting the board without any delay would solve the issue. Even if you turn off animation with setPosition cause the problem with stacking animation because all transitions are still in the queue.

**Comment by shaack** [comment]
In that case this is a feature quest for a "flush queue" feature?

**Comment by tbazelczuk** [comment]
Right, I think that would solve the issue.

Many thanks  :)

**Comment by shaack** [comment]
Does anyone needs this anymore?

**Comment by tbazelczuk** [comment]
yes :)

**Comment by shaack** [comment]
Do you need more a "flush queue", "reset queue or "stop queue" feature. Is the state of the pieces important after resetting?

**Comment by shaack** [comment]
Does `chessboard.positionAnimationsQueue.stop = true` works?
