### ISSUE TITLE
Console errors on pointer move after destroying board with selected piece

### ISSUE THREAD

**Issue by cvn** [shaack/cm-chessboard#9]
Hi @shaack,

With version 2.12.4, when I have a piece selected and I call `destroy()`, I get errors on pointer move.

```js
import {Chessboard} from "cm-chessboard";
const chessboard = new Chessboard(document.getElementById('myBoard'), {}, (board) => {
  // simulate selecting a piece
  board.view.moveInput.setStatus(0)
  board.view.moveInput.setStatus(1, {index: 0, piece: 'wr', point: {x:0,y:0}, type: 'mousedown'})
});
setTimeout(() => chessboard.destroy(), 1000);
```
Now move the mouse pointer around the page, and this errors appears many times in the console:
```
Uncaught TypeError: Cannot read property 'markers' of null
    at ChessboardView.drawMarkers (ChessboardView.js?8d80:307)
    at drawMarkersDebounce.setTimeout (ChessboardView.js?8d80:299)
```
Click anywhere and this error appears:
```
Uncaught TypeError: Cannot read property 'squares' of null
    at ChessboardView.drawPiecesDebounced (ChessboardView.js?8d80:241)
    at ChessboardMoveInput.onPointerUp (ChessboardMoveInput.js?a535:313)
```
If you drag the piece instead of just selecting it, you get the same errors, and the dragablePiece stays visible and follows the pointer.

I think the problem is that the [event listeners](https://github.com/shaack/cm-chessboard/blob/204336a92b8168fb530ed5c470cd5ba91c6e60ea/src/cm-chessboard/ChessboardMoveInput.js#L57-L76) and [dragablePiece](https://github.com/shaack/cm-chessboard/blob/204336a92b8168fb530ed5c470cd5ba91c6e60ea/src/cm-chessboard/ChessboardMoveInput.js#L177) in ChessboardMoveInput aren't being removed when destroy is called.

**Comment by shaack** [comment]
Thanks for reporting. It should be fixed now. :)

**Comment by cvn** [comment]
Thank you @shaack! It works for me.
