### ISSUE TITLE
Any chance you could add support for L-shaped arrows for the knights?

### ISSUE THREAD

**Issue by vesper8** [shaack/cm-chessboard#96]
I was wondering how difficult this might be to add, or if anyone has managed to do this? chess.com, and I believe Lichess as well but not sure, has support for L-shaped arrows that mimic the movement of knights.

I guess these arrows would then take in 3 coordinates instead of two, shouldn't be too hard to accomplish IMO. Maybe it's already possible and I missed it.

Any feedback on this @barakmich?

Many thanks!

**Comment by shaack** [comment]
I don't think so, sorry
